# feature extractor
run: 2
model_name: 'embedding_unet'
backbone:
  name: UNet2D
  in_channels: 1
  out_channels: 16
  # use Groupnorm instead of Batchnorm for DSB; Batchnorm introduces artifacts around nuclei due to the difference
  # in intensity distribution between images with large and small cells
  layer_order: gcr
  num_groups: 8
  f_maps: [8, 32, 64, 128, 256]
  #conv_padding: 0
  final_sigmoid: false
  is_segmentation: false
load_pretrained: false
lr: 1e-3

trainer:
  n_iterations: 20000  # number of total iterations
  batch_size: 10  # batch size for feature extractor warmup

  patch_shape: [100, 100]
  patch_stride: [128, 128]
  reorder_sp: true
  patch_manager: none # rotated, no_cross, none

